name: NASA Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    env:
      CI: true
      MONGO_URL: mongodb://localhost/nasa
    strategy:
      matrix:
        node-version: [14.x, 16.x]
        mongodb-version: [ '4.4' ]
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use MongoDB from githhub actions
        uses: supercharge/mongodb-github-action@v1.6.0
        with:
           mongodb-version: ${{ matrix.mngodb-version }}
      - run: npm install
      - run: npm run build --prefix client